### ISSUE TITLE
Catchpoint blog migration

### ISSUE THREAD

**Issue by doffymingozzz** [n3m351d4/GitBook#1]
Hi!

It’s Gleb from Catchpoint.com.

I've noticed that your website links to our old blog, which we’re currently migrating from a subdomain to the main domain. The reason I’m reaching out is to make sure you won’t have a 404 error on your website.

You have a link to our old blog on the following pages:
https://notes.n3m3515.space/networks-1/translations/izuchenie-mqtt-s-ispolzovaniem-wireshark
https://notes.n3m3515.space/networks-1/translations/mqtt-nervnaya-sistema-iot

I wonder if you’d be able to replace it with the new one: 
https://www.catchpoint.com/blog/2018-outages
https://www.catchpoint.com/blog/mqtt-iot

Thanks for linking to Catchpoint.com!

Please don’t hesitate to contact me if something comes up v-gkapusto@catchpoint.com!

Best, 
Gleb

**Comment by n3m351d4** [comment]
Hello!
I have changed links about mqtt, but the first link is not correct and directs to another article, the right link was https://www.catchpoint.com/blog/wireshark-mqtt and I already changed it.
Thank you!

**Comment by doffymingozzz** [comment]
Thanks!
